name: Build .NET SDK

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'dotnet VMR branch name'
        required: true
        type: string

jobs:
  run:
    runs-on: ubuntu-latest

    steps:

    - name: Maximize build space
      uses: AdityaGarg8/remove-unwanted-software@v4.1
      with:
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        remove-cached-tools: 'true'        

    - name: Clone repository
      run: |
        git clone --depth 1 -b ${{ inputs.branch }} https://github.com/dotnet/dotnet

    - name: Apply patches
      run: |
        wget https://patch-diff.githubusercontent.com/raw/dotnet/sdk/pull/46720.diff
        patch -d dotnet -p4 -i ${{ github.workspace }}/46720.diff
        wget https://gist.githubusercontent.com/am11/12569a638a9a1c54a9c190ae7ef6ebfc/raw/851e15f096fcc215bc32a9eb79fb0eb9ba0d1656/runtime.diff
        patch -d dotnet/src/runtime -p1 -i ${{ github.workspace }}/runtime.diff
        wget https://github.com/dotnet/aspnetcore/commit/b2f804b21ea70ba3479210a16f41de3898c5da5f.patch
        patch -d dotnet/src/aspnetcore -p1 -i ${{ github.workspace }}/b2f804b21ea70ba3479210a16f41de3898c5da5f.patch
        wget https://github.com/dotnet/aspnetcore/commit/a44df9b2312c2daf664ddb55b64243717e2ca80b.patch
        patch -d dotnet/src/aspnetcore -p1 -i ${{ github.workspace }}/a44df9b2312c2daf664ddb55b64243717e2ca80b.patch

    - name: Build
      run: |
        docker run --platform linux/amd64 --rm -v${{ github.workspace }}/dotnet:/dotnet -e ROOTFS_DIR=/crossrootfs/riscv64 -e DISABLE_CROSSGEN=1 \
          mcr.microsoft.com/dotnet-buildtools/prereqs:azurelinux-3.0-net10.0-cross-riscv64 \
          sh -c 'cd /dotnet && ./prep-source-build.sh && ./build.sh --clean-while-building -sb --two-stage-runtime-build /p:TargetOS=linux /p:TargetArchitecture=riscv64 /p:Crossbuild=true'

    - name: Upload .NET
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-sdk-linux-riscv64
        path: "${{ github.workspace }}/dotnet/artifacts/assets/Release/dotnet-sdk-*"
